### PR TITLE
Add New Extension: wvlet flow-style query language

### PR DESCRIPTION
**Pull request by lmangani**
### DuckDB [wvlet](https://wvlet.org/) Community Extension
[Wvlet](https://wvlet.org/) a cross-SQL flow-style query language for functional data modeling and interactive data analysis. 

This extension adds support for executing **wvlet** scripts directly through DuckDB SQL.

### Status
- Very experimental. PR open just to test the custom library binding.
- Untested. Will work with wvlet developers if there's interest.

### Examples
```sql
D SELECT * FROM wvlet('select 1');
-- wvlet version=0.0.0+1-e9ceb08b+20241124-0132, src=01JDF4E4BK6RA89RB7RTN4V0NV.wv:1
select 1
┌───────┐
│   1   │
│ int32 │
├───────┤
│     1 │
└───────┘

D SELECT * FROM wvlet('select version()');
-- wvlet version=0.0.0+1-e9ceb08b+20241124-0132, src=01JDF4E6NJ94JG6D5K95REX3S2.wv:1
select version() 
┌─────────────┐
│ "version"() │
│   varchar   │
├─────────────┤
│ v1.1.3      │
└─────────────┘

D CREATE TABLE t1 AS SELECT 42 AS i, 84 AS j;
D SELECT * FROM wvlet('from t1');
-- wvlet version=0.0.0+1-e9ceb08b+20241124-0132, src=01JDF4ECWR417HJQNG1GSHCGH0.wv:1
select * from t1
┌───────┬───────┐
│   i   │   j   │
│ int32 │ int32 │
├───────┼───────┤
│    42 │    84 │
└───────┴───────┘

```

### CODE REVIEW

**Comment by lmangani** [comment]
Ah... no more build runners for PR/drafts? 😢

**Comment by carlopi** [comment]
> Ah... no more build runners for PR/drafts? 😢

That should not be the case, I can't think of something our side, possibly I have seen similar behaviour when YAML is corrupted, but I can't see what's going on here. I will check tomorrow.

**Comment by carlopi** [comment]
Did you by any chance manage to have it build? 
Otherwise I can re-open and track this down.

And would you like this to be merged (once I figure out the problem with build).

**Comment by lmangani** [comment]
Thanks @carlopi. This is just a build draft with no intention to merge as of yet - not until the necessary prs are merged on the vwlet library side anyways but so far I got no responses. Probably only to be used as an example.

**Comment by lmangani** [comment]
~~@carlopi would you rather have this closed and re-opened in the future to keep the repo clean? development in wvlib is still ongoing and it might take a good while~~

🎉  https://github.com/wvlet/wvlet/commit/4e97b1d6af192ecbdca0b6c85dab9b909aef91a5

**Pull request closed without merging**
