### PR TITLE
Add pyroscope extension

### PR DESCRIPTION
**Pull request by lmangani**
### Description
Experimental Pyroscope extension for continous profiling of DuckDB 👁️ compatibly with pprof backends such as Grafana Pyroscope and of course with our magic polyglot observability stack [qryn](https://qryn.dev)

### Usage
```sql
---- Start the tracer, requires backend URL
D SELECT * FROM trace_start('https://pyroscope:4000');

---- Do a bunch of quack-fu queries ...

---- Stop the tracer
D SELECT * FROM trace_stop();
```

## Glory Shot in Pyroscope
Profiling data is streamed in realtime to the backend

image

### CODE REVIEW

**Comment by lmangani** [comment]
The builder test is not triggered. Is there something missing on our behalf?

**Comment by lmangani** [comment]
mmm yeah something must be wrong, the PR shows no conflicts without running any action test....

**Comment by samansmink** [comment]
Looks very cool! Thanks @lmangani

**Comment by lmangani** [comment]
Thanks @samansmink curious about your feedback from the nest! there's also a raw https://github.com/quackscience/duckdb-extension-pprof if you're interested in the raw files w/o the Pyroscope API in the middle. Not sure if we should release it - happy to hear your opinion. Sadly they cannot be merged in the same extension due to conflicts between the libraries in rust I couldn't resolve (yet).

**Pull request merged**
