### PR TITLE
DuckDB GSheets

### PR DESCRIPTION
**Pull request by archiewood**

### CODE REVIEW

**Comment by carlopi** [comment]
Welcome to the community extensions!

**Comment by archiewood** [comment]
is there anything else I need to do here?

```
install gsheets from community;
HTTP Error: Failed to download extension "gsheets" at URL "http://community-extensions.duckdb.org/v1.1.1/osx_arm64/gsheets.duckdb_extension.gz" (HTTP 403)

Candidate extensions: "postgres", "inet", "https", "delta", "s3"
```

**Comment by carlopi** [comment]
Extensions are, at the moment, only built and distributed in the latest stable duckdb version, that is `v1.1.2`.

Once a new release hits, old deployed extensions stays alive, but in the state they were last published.

I checked earlier from OSX CLI on v1.1.2, works as a charm.

**Comment by carlopi** [comment]
This might need better documentation, if it was not clear enough to you.

**Comment by archiewood** [comment]
aha i need to upgrade them!

**Comment by archiewood** [comment]
worked TY

**Pull request merged**
