### PR TITLE
Flockmtl

### PR DESCRIPTION
**Pull request by queryproc**
This PR adds `FlockMTL`, a DuckDB extension, as a community supported extension. 

`FlockMTL` introduce `PROMPT`(s) and `MODEL`(s) as DDL constructs and multiple LLM scalar functions, namely `llm_complete`, `llm_complete_json`, `llm_filter`, and `llm_embedding`.

The current ref points to the following release: https://github.com/dsg-polymtl/duckdb-flockmtl/releases/tag/v0.1.0

### CODE REVIEW

**Comment by queryproc** [comment]
Doing: Fixing windows

EDIT: fixed the issue! (Will bump the ref and @ you once ready for the build)

**Comment by anasdorbani** [comment]
@samansmink can you pls run the builds the extension is ready?

**Review by carlopi — COMMENTED** [review]
Thanks!

Currently this fails one test for generating docs, since the assumption is that extensions can be loaded without other dependencies, but there a missing env variable makes so the extension can't load.

I will have a look at making doc generation step take a setup step, so that a fake env variable can for example be added. This might make sense also in other cases to set invariants or so. Or maybe make so that they can be skipped. I will come back on this.

**Comment by queryproc** [comment]
> Thanks!
> 
> Currently this fails one test for generating docs, since the assumption is that extensions can be loaded without other dependencies, but there a missing env variable makes so the extension can't load.
> 
> I will have a look at making doc generation step take a setup step, so that a fake env variable can for example be added. This might make sense also in other cases to set invariants or so. Or maybe make so that they can be skipped. I will come back on this.

@carlopi Okay. Thank you! Will load a garbage env var value for now to be able to pass and let the extension fail on function use.

**Comment by queryproc** [comment]
@carlopi added the fix to skip the env var loading. We can run the workflow!

p.s. might be worth adding this test to the original GH action extension template.

**Pull request merged**
