### PR TITLE
Add xxhash extension written in Go with the C API. 

### PR DESCRIPTION
**Pull request by ajzo90**

### CODE REVIEW

**Comment by ajzo90** [comment]
Having trouble with building the docs. Complains about missing .so file. 
`IO Error: Extension "build/extensions/v1.1.0/linux_amd64_gcc4/xxhash.duckdb_extension" could not be loaded: libduckdb.so: cannot open shared object file: No such file or directory`

Worth mentioning is that I'm using the new C API extensions, perhaps related to that?

https://github.com/ajzo90/duckdb-community-extensions/actions/runs/10886389437/job/30207261474

**Comment by carlopi** [comment]
What's failing is loading the extension in DuckDB itself, I guess locally works since you have the `libduckdb.so` or equivalent in the right path, but that is not the case for the environment where the docs are generated.

I think you do need to link in libduckdb in your extension explicitly to make this work.

**Comment by ajzo90** [comment]
Giving up on this for now, succeeded building the extension with statically linking duckdb, but got stuck on another error instead.

**Comment by ajzo90** [comment]
It is now stuck in 
```Run ./duckdb -c "SET extension_directory = 'build/extension_dir'; FORCE INSTALL 'build/downloaded/$NAME.duckdb_extension';"
IO Error: Extension "build/downloaded/xxhash.duckdb_extension" could not be loaded: build/downloaded/xxhash.duckdb_extension: cannot allocate memory in static TLS block`
```

**Comment by carlopi** [comment]
Hi, I have to say I am not exactly what's happening here, it might about some linking flag or so, unsure.

I understand @taniabogatsch is taking a look on how to create go extensions with the C API, so help might be coming!

**Comment by taniabogatsch** [comment]
I haven't looked into building Go extensions with the current extension template.
But indeed, I am looking into building them with the new extension C API.

**Pull request closed without merging**
