### PR TITLE
Update httpserver ref

### PR DESCRIPTION
**Pull request by lmangani**
## Authentication methods for API

- X-API-Key header: 'yoursecrettoken`
- Basic Authentication header: `username:password`

#### Basic Auth
```sql
SELECT httpserve_start('localhost', 9999, 'your_api_key_or_user:pass');
```

```bash
curl -X POST -d "SELECT 'hello', version()" "http://user:pass@localhost:9999/"
```

#### Token Auth
```sql
SELECT httpserve_start('localhost', 9999, 'supersecretkey');
```

```
curl -X POST --header "X-API-Key: supersecretkey" -d "SELECT 'hello', version()" "http://localhost:9999/"
```

### CODE REVIEW

**Review by carlopi — CHANGES_REQUESTED** [review]
There are currently merge conflicts, can you merge or rebase with `main`?

**Comment by lmangani** [comment]
> There are currently merge conflicts, can you merge or rebase with `main`?

Are you referring to the community-extensions repo or the extension itself? I can't see errors so I'm not sure

Edit the community-extensions fork seems in sync
image

**Comment by carlopi** [comment]
I had:
image

but merge was available, all good.

**Comment by lmangani** [comment]
Apologies if this was due to the PR update mid-action. Will be more careful next time 😉

**Pull request merged**
